import { render, screen } from "@testing-library/react";
import { BrowserRouter } from "react-router-dom";
import ResultPage from "../pages/ResultPage";

jest.mock("../api/axiosInstance");
jest.mock("../components/GaugeChart", () => () => <div data-testid="gauge-chart" />);
jest.mock("../components/WordExplanation", () => () => <div data-testid="word-explanation" />);
jest.mock("../components/BatchSummaryChart", () => () => <div data-testid="batch-summary-chart" />);
jest.mock("../components/BatchWordAnalysis", () => () => <div data-testid="batch-word-analysis" />);
jest.mock("../components/AnimatedContainer", () => ({
  StaggerContainer: ({ children }) => <div data-testid="stagger-container">{children}</div>,
  StaggerItem: ({ children }) => <div data-testid="stagger-item">{children}</div>,
}));

const mockSingleState = {
  type: "single",
  text: "This is a test text about fake news.",
  label: "fake",
  confidence: 0.87,
  model_used: "Hybrid Random Forest",
  threshold: 0.5,
  timestamp: Date.now(),
  processing_time_ms: 123,
  word_contributions: [
    { word: "fake", contribution: 0.25, direction: "fake" },
    { word: "news", contribution: 0.15, direction: "fake" },
  ],
  category_hints: [
    { category: "Urgency / Scarcity", count: 2, matched_words: ["urgent", "now"] },
  ],
  meta_indicators: [
    { name: "link_count", value: 0, description: "No links found" },
  ],
};

const mockSingleRealState = {
  ...mockSingleState,
  label: "real",
  confidence: 0.92,
  word_contributions: [
    { word: "weather", contribution: 0.2, direction: "real" },
  ],
  category_hints: [],
};

const mockBatchState = {
  type: "batch",
  model: "hybrid",
  threshold: 0.5,
  batchResult: {
    total_rows: 5,
    results: [
      { index: 0, text: "Real news article", label: "real", confidence: 0.95, word_contributions: [], category_hints: [], meta_indicators: [] },
      { index: 1, text: "Fake news article", label: "fake", confidence: 0.88, word_contributions: [], category_hints: [], meta_indicators: [] },
      { index: 2, text: "Another real one", label: "real", confidence: 0.91, word_contributions: [], category_hints: [], meta_indicators: [] },
      { index: 3, text: "Error row", label: "error", confidence: 0, reason: "Empty text" },
      { index: 4, text: "Final real article", label: "real", confidence: 0.78, word_contributions: [], category_hints: [], meta_indicators: [] },
    ],
    model_used: "Hybrid Random Forest",
    processing_time_ms: 1500,
  },
};

// Mock useLocation
const mockLocation = (state) => ({
  pathname: "/result",
  state,
  search: "",
  hash: "",
  key: "default",
});

let mockLocationState = null;

jest.mock("react-router-dom", () => ({
  ...jest.requireActual("react-router-dom"),
  useLocation: () => mockLocation(mockLocationState),
  useNavigate: () => jest.fn(),
}));

const renderResultPage = () =>
  render(
    <BrowserRouter>
      <ResultPage />
    </BrowserRouter>
  );

describe("ResultPage", () => {
  beforeEach(() => {
    jest.clearAllMocks();
    // Reset localStorage mock
    const store = {};
    jest.spyOn(Storage.prototype, "getItem").mockImplementation((key) => store[key] ?? null);
    jest.spyOn(Storage.prototype, "setItem").mockImplementation((key, val) => { store[key] = val; });
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  test("shows no data message when no state provided", () => {
    mockLocationState = null;
    renderResultPage();
    expect(screen.getByText("No prediction data found")).toBeInTheDocument();
    expect(screen.getByText(/Make a prediction first/)).toBeInTheDocument();
  });

  test("shows error alert on single result page", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByText(/These predictions are generated by machine learning models/)).toBeInTheDocument();
  });

  test("shows gauge chart for single prediction", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByTestId("gauge-chart")).toBeInTheDocument();
  });

  test("shows confidence percentage", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByText("87.0% confidence")).toBeInTheDocument();
  });

  test("shows confidence tier: Likely for 0.87", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByText(/Likely Fake/)).toBeInTheDocument();
  });

  test("shows model name and processing time", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByText(/Hybrid Random Forest/)).toBeInTheDocument();
    expect(screen.getByText(/123 ms/)).toBeInTheDocument();
  });

  test("shows Fake Cause Categories section", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByText("Fake Cause Categories")).toBeInTheDocument();
  });

  test("shows all 5 fallback categories even when only 1 has matches", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByText("Urgency / Scarcity")).toBeInTheDocument();
    expect(screen.getByText("Emotional Manipulation")).toBeInTheDocument();
    expect(screen.getByText("Conspiracy Language")).toBeInTheDocument();
    expect(screen.getByText("Financial Scam")).toBeInTheDocument();
    expect(screen.getByText("Health Misinformation")).toBeInTheDocument();
  });

  test("shows matched word count for category hint", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByText(/Matched 2 words ▸/)).toBeInTheDocument();
  });

  test("shows Analysis Coverage section", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByText("Analysis Coverage")).toBeInTheDocument();
  });

  test("shows word explanation component", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByTestId("word-explanation")).toBeInTheDocument();
  });

  test("shows Compare Models button", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByText("Compare Models")).toBeInTheDocument();
  });

  test("shows Download PDF button", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByText("Download PDF")).toBeInTheDocument();
  });

  test("shows thumbs up/down feedback buttons", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    const thumbsUp = screen.getByTestId("ThumbUpIcon");
    const thumbsDown = screen.getByTestId("ThumbDownIcon");
    expect(thumbsUp).toBeInTheDocument();
    expect(thumbsDown).toBeInTheDocument();
  });

  test("shows threshold value", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByText(/Threshold: 0.50/)).toBeInTheDocument();
  });

  test("real prediction shows green text and correct tier", () => {
    mockLocationState = mockSingleRealState;
    renderResultPage();
    expect(screen.getByText(/Highly Real/)).toBeInTheDocument();
    expect(screen.getByText("92.0% confidence")).toBeInTheDocument();
  });

  test("batch view shows all row results", () => {
    mockLocationState = mockBatchState;
    renderResultPage();
    expect(screen.getByText(/Row Results/)).toBeInTheDocument();
    expect(screen.getByText("#1")).toBeInTheDocument();
    expect(screen.getByText("#5")).toBeInTheDocument();
  });

  test("batch view shows prediction summary counts", () => {
    mockLocationState = mockBatchState;
    renderResultPage();
    expect(screen.getByText("Prediction Summary")).toBeInTheDocument();
    expect(screen.getByText("3")).toBeInTheDocument(); // real count
    expect(screen.getByText("1")).toBeInTheDocument(); // fake count
  });

  test("batch view shows error chip when errors exist", () => {
    mockLocationState = mockBatchState;
    renderResultPage();
    expect(screen.getByText(/Errors: 1/)).toBeInTheDocument();
  });

  test("batch view shows batch summary chart", () => {
    mockLocationState = mockBatchState;
    renderResultPage();
    expect(screen.getByTestId("batch-summary-chart")).toBeInTheDocument();
  });

  test("batch view shows download CSV button", () => {
    mockLocationState = mockBatchState;
    renderResultPage();
    expect(screen.getByText("Download CSV")).toBeInTheDocument();
  });

  test("back to predict button is present for single view", () => {
    mockLocationState = mockSingleState;
    renderResultPage();
    expect(screen.getByText("Back to Predict")).toBeInTheDocument();
  });

  test("back to predict button is present for batch view", () => {
    mockLocationState = mockBatchState;
    renderResultPage();
    expect(screen.getByText("Back to Predict")).toBeInTheDocument();
  });
});
